### ISSUE TITLE
How to Use Cart ?

### ISSUE THREAD

**Issue by maulayyacyber** [melihovv/laravel-shopping-cart#10]
im getting this error on Laravel 7

<img width="598" alt="Screen Shot 2020-03-28 at 07 11 28" src="https://user-images.githubusercontent.com/11194525/77809700-70b40100-70c3-11ea-96f3-826a3203309d.png">

**Comment by melihovv** [comment]
Hi, @maulayyacyber 
Enhance docs in this pr https://github.com/melihovv/laravel-shopping-cart/pull/12
Check it out
