### ISSUE TITLE
Adding item to cart then using Cart::count() on blade view does not work

### ISSUE THREAD

**Issue by JamieCee20** [melihovv/laravel-shopping-cart#16]
In my function I add an item to the cart, this works as it should and have done multiple checks to ensure the right data is also being passed in, then I redirect to a cart page and attempt to do Cart::count() > 0 to display information if the cart isnt empty except on the blade it returns the cart as empty?

**Comment by melihovv** [comment]
I think you should call `Cart::restore()` to load data from storage to memory before you call `Cart::count()`.
