### ISSUE TITLE
Colum ID cannot be null error

### ISSUE THREAD

**Issue by JamieCee20** [melihovv/laravel-shopping-cart#17]
My code:

    public function store(User $user, Request $request)
    {
        // dd($request);
        $id = $request->id;
        $name = $request->name;
        $price = $request->price;

        $contentCart = Cart::instance('shopping')->add($id, $request->name, $request->price, 1);

        if(Cart::has($contentCart->getUniqueId())) {
            Cart::store($user->id)->content();
        }
        // Cart::store($user->id)->content();
        // return redirect()->route('cart.index')->with('success', 'Item was added to your cart');
    }

DD() has proven request ID is not null, it just wont store apparently.

**Comment by JamieCee20** [comment]
And when I run Cart::content();

{"bb4a6db4295d6be8bd12791ed5650087":{"unique_id":"bb4a6db4295d6be8bd12791ed5650087","id":"14","name":"Laptop 14","price":599999,"quantity":1,"options":[]}}

**Comment by melihovv** [comment]
I don't understand, what the problem is?

**Comment by melihovv** [comment]
Close due to inactivity
