### ISSUE TITLE
Hi i keep getting Controllers not found error

### ISSUE THREAD

**Issue by zcwessels** [melihovv/laravel-shopping-cart#7]
Symfony\Component\Debug\Exception\FatalThrowableError Class 'App\Http\Controllers\Cart' not found
![image](https://user-images.githubusercontent.com/31216542/70032322-e563ac80-15b5-11ea-89c4-1840f5eedebe.png)

**Comment by melihovv** [comment]
Use `\Cart::add` instead of `Cart::add`. `\Cart` is a facade.

**Comment by OscarTango1995** [comment]
Not working for me im on laravel 6.2

**Comment by melihovv** [comment]
try `Melihovv\ShoppingCart\Facades\Cart`
